services:
  pppwn:
    build:
      context: .
    container_name: pppwn
    network_mode: "host"
    environment:
      - INTERFACE=eth0
      - FIRMWAREVERSION=1100
    cap_add:
    - NET_ADMIN
    privileged: true
    volumes:
      - ./pppwn:/pppwn
      - ./nginx/default.conf:/etc/nginx/http.d/default.conf
      - ./supervisord.conf:/etc/supervisord.conf
      - ./html:/var/www/html
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 96M
